---
title: "Introduction to RFM"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to RFM}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

```{r, echo=FALSE, message=FALSE}
library(segmentr)
library(knitr)
library(kableExtra)
library(magrittr)
library(dplyr)
options(knitr.table.format = "html") 
options(tibble.width = Inf)
```

## RFM 

```{r rfm_table, eval=FALSE}
analysis_date <- lubridate::as_date('2006-12-31', tz = 'UTC')
rfm_result <- rfm_table(rfm_data, customer_id, order_date, revenue, analysis_date)
rfm_result 
```

```{r rfm_table2, eval=TRUE, echo=FALSE}
analysis_date <- lubridate::as_date('2006-12-31', tz = 'UTC')
rfm_result <- rfm_table(rfm_data, customer_id, order_date, revenue, analysis_date)
rfm_result %>%
  use_series(rfm) %>%
  slice(1:10) %>%
  kable() %>%
  kable_styling()
```

### Heat Map

```{r heatmap, fig.align='center', fig.width=7, fig.height=7}
rfm_heatmap(rfm_result)
```

### Bar Chart

```{r barchart, fig.align='center', fig.width=7, fig.height=7}
rfm_bar_chart(rfm_result)
```

## Histogram

```{r rfmhist, fig.align='center', fig.width=7, fig.height=7}
rfm_histograms(rfm_result)
```

## Customers by Orders

```{r rfmorders, fig.align='center', fig.width=7, fig.height=7}
rfm_order_dist(rfm_result)
```

### Scatter Plots

#### Recency vs Monetary Value

```{r mr, fig.align='center', fig.width=7, fig.height=7}
rfm_rm_plot(rfm_result)
```

#### Frequency vs Monetary Value

```{r fm, fig.align='center', fig.width=7, fig.height=7}
rfm_fm_plot(rfm_result)
```

#### Recency vs Frequency 

```{r fr, fig.align='center', fig.width=7, fig.height=7}
rfm_rf_plot(rfm_result)
```
